name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hesoyam999/octa:www
    - name: push docker image
      run: docker login -u hesoyam999 -p ${{ secrets.MY_USER }} && docker push hesoyam999/octa:www
